// Neon district LP demo data — 8 LPs (haejun, kai, jian, nia, levi, damya, lise, lana)
// Format: 100% mirrors LP_FULL.kael golden sample in lp_demo.html
Object.assign(LP_FULL, {

  haejun: {
    title: '5시 32분, 라면 두 그릇',
    profileBg: 'img/lp/haejun_entry/profile_bg.png',
    entryThumb: 'img/lp/haejun_entry/scene1.png',
    rewards: [
      '감정 조각 +8',
      '싱크율 0% → 5%',
      '키메모리 해금: "두 그릇 라면" / "형 시계의 톱니"',
      '내일 새벽 5시 30분, 6km 코스 같이 뛰기'
    ],
    chat: [
      { type: 'image', src: 'img/lp/haejun_entry/header.png', caption: '새벽 5시 32분 · 옥상 자판기 앞' },
      { type: 'narration', text: '새벽 5시 32분. 6km 러닝을 끝낸 그가 옥상 자판기 앞에 서 있다. 손에 컵라면 두 그릇. 한 그릇은 다 끓었고, 한 그릇은 막 뜨거운 물을 부은 참. 회색 후디 위에 셔츠. 회사에선 안 보이는 차림. 너를 보고 한 박자 늦게 어깨 한 칸이 내려간다.' },
      { type: 'lp', text: '...어, 늦으셨네요. 한 그릇 더 끓이려고 물 받아두긴 했는데, 그쪽 거예요. 부담은 안 가지셔도 돼요. 어차피 자판기는 두 개씩 안 빠지면 안 익거든요.' },
      { type: 'narration', text: '거짓말이다. 자판기는 한 그릇씩도 잘 익는다. 본인도 알고 있는 듯 한 박자 늦게 옅게 웃는다.' },
      { type: 'lp', text: '...아니, 거짓말이에요. 그냥 두 그릇 끓이고 싶었어요. 회사에선 못 하니까요.' },
      { type: 'user', text: '회사에선 어떤데요?' },
      { type: 'narration', text: '컵라면 뚜껑을 손가락으로 한 번 누른다. 면이 다 익는 정확한 30초.' },
      { type: 'lp', text: '회사에선 점심 10분이에요. 혼자 먹는 점심이요. ...옥상은 5시 32분이고요. 이 시간엔 사람이 없어서요. 오늘은 그쪽이 한 명 있긴 하네요.' },
      { type: 'user', text: '같이 라면 먹는 거 잘 안 하시나봐요.' },
      { type: 'narration', text: '뚜껑을 연다. 김이 올라온다. 한 그릇을 자기 옆 난간에 놓고, 한 그릇은 너 쪽에 내민다.' },
      { type: 'lp', text: '안 해요. 정확히는, 못 해요. 회사에서 1위 자리 안 내려와야 해서요. 옆에 사람 들이는 게 좀… 어렵거든요. 옥상이 그게 풀리는 자리고요.' },
      { type: 'narration', text: '손목의 시계를 한 번 본다. 1980년대 거. 표정이 살짝 풀린다.' },
      { type: 'lp', text: '이 시계, 형 거예요. 어릴 때 잃었어요. 4개월째 분해하고 있는데 손에 익지가 않네요. ...그쪽도 한번 만져볼래요? 안 망가져요.' },
      { type: 'user', text: '...만져봐도 돼요?' },
      { type: 'narration', text: '시계를 풀어 너 손바닥에 직접 올려준다. 그 손이 한 번 미끄러지듯 닿았다가 떨어진다. 자각 후 어색하게 한 번 웃는다.' },
      { type: 'lp', text: '...떨어뜨려도 괜찮아요. 분해 중이라서요. ...아니, 거짓말. 떨어지면 좀 그래요. 근데 그쪽이 떨어뜨리면 그건 또 괜찮아요. 이상하죠.' },
      { type: 'lp', text: '내일 5시 30분, 6km 코스 처음부터 같이 가실래요? 천천히 가요. 그쪽 페이스에 맞출게요. 제 페이스로만 4년을 도느라, 다른 페이스가 어떤지 까먹었거든요.' },
      { type: 'user', text: '같이 갈게요.' },
      { type: 'narration', text: '한 박자 늦게 입꼬리 한쪽이 부드럽게 올라간다. 컵라면 김이 두 그릇 사이에서 한 자리에 모인다.' },
      { type: 'lp', text: '...좋네요. 그럼 내일 5시 30분 옥상 입구에서요. 한 그릇 더 끓일게요. 라면이 두 개여야 자판기 잘 익는다고 그쪽한테 또 거짓말할 거예요.' },
      { type: 'modal' }
    ],
    vn: [
      { type: 'bg', img: 'img/lp/haejun_entry/scene1.png' },
      { type: 'char', show: false },
      { type: 'gm', text: '다음날 새벽 5시 30분 옥상 입구. 회색 후디 위에 셔츠를 걸친 이해준이 가벼운 러닝화 차림으로 너를 기다린다. 손목엔 1980년대 시계, 한 손엔 작은 물병 두 개. 회사에서의 차콜 쓰리피스가 아니다. 이 모습을 본 사람은 그쪽이 처음이다.' },
      { type: 'char', show: true, src: 'img/lp/haejun_entry/char_haejun.png' },
      { type: 'narration', text: '너를 보고 어깨 한 칸이 내려간다. 회사에선 보지 못한 표정.' },
      { type: 'lp', text: '왔네요. 늦지 않으셨고요. ...오늘은 천천히 가요. 6km는 사실 좀 길어서, 그쪽 페이스로 가면 한 시간 정도 걸릴 거예요. 저는 그게 더 좋아요. 평소엔 32분에 끝나거든요.' },
      { type: 'narration', text: '물병 한 개를 너에게 건넨다. 자기 거랑 같은 종류, 같은 차가움.' },
      { type: 'lp', text: '32분에 끝나면 그게 끝이에요. 한 시간이면, 그게 두 배예요. 두 배는 처음이고요.' },
      { type: 'gm', text: '6km 코스가 시작된다. 평소 그가 32분에 끝내는 길. 오늘은 한 시간이 걸린다.' },
      { type: 'narration', text: '그가 평소 페이스의 절반으로 달린다. 너와 나란히. 옆으로 살짝 기울어 너를 본다.' },
      { type: 'lp', text: '4년 동안 이 코스에서 다른 사람이랑 같이 뛴 적이 없어요. 한 번도요. ...그쪽이랑 처음 뛰는 거예요. 가문 룰이 코스도 혼자 도는 거였거든요. 오늘은 그 룰 어긴 날이에요. 누구한테 안 들켜야 하는데, 그쪽한텐 들켜도 괜찮아요.' },
      { type: 'narration', text: '코스 중간 작은 벤치. 그가 먼저 멈춘다. 호흡은 가쁘지 않다. 일부러 멈춘 거다.' },
      { type: 'lp', text: '여기서 5분만 쉴게요. 평소엔 안 쉬어요. 그쪽 페이스에 맞춰 쉬어보는 거예요. ...의외로 좋네요. 평소엔 안 본 풍경이 보여요. 새벽 6시엔 뭐가 보이는지 4년 동안 몰랐어요. 32분 안에 다 도느라요.' },
      { type: 'choices', options: [
        { label: '"형이랑 이 코스 같이 뛰셨어요?"', branch: 'A' },
        { label: '"풍경 보고 가요. 5분 더 쉬어도 돼요"', branch: 'B' },
        { label: '말없이 그의 손에서 물병을 받아 한 모금 마신다', branch: 'C' }
      ]},
      { type: 'char', show: true, src: 'img/lp/haejun_entry/char_haejun_smile.png', branch: 'C' },
      { type: 'narration', text: '말없이 물병을 받아 든 너에게 그가 한 박자 늦게 한 번 웃는다. 회사에선 안 보이는 어색한 풋풋함.', branch: 'C' },
      { type: 'lp', text: '...뭐예요, 그게. 답을 안 하시고 그냥 받아 마시는 거. 4년 동안 누구한테 그렇게 받아본 적 없어요. 평소엔 답을 한 번씩 받아야 다음으로 넘어갔거든요.', branch: 'C' },
      { type: 'narration', text: '벤치에 한 자리 비워두고 살짝 옆으로 비킨다. 같이 앉을 수 있는 자리.', branch: 'C' },
      { type: 'lp', text: '앉아요. 5분만요. ...아니, 더 있어도 돼요. 오늘은 다음 코스 안 돌아도 돼요. 그쪽이랑 5분 더 있는 게 다음 코스보다 좋아서요.', branch: 'C' },
      { type: 'char', show: true, src: 'img/lp/haejun_entry/char_haejun_smile.png', branch: 'A' },
      { type: 'narration', text: '형 얘기에 그가 한 박자 멈춘다. 손목의 시계를 한 번 만진다. 표정은 부드럽게 풀려 있다.', branch: 'A' },
      { type: 'lp', text: '같이 안 뛰었어요. 형은 일찍 갔거든요. 가문 승계 투쟁에서요. 그래서 제가 혼자 뛰는 코스가 됐어요. ...오늘이 형이 못 뛴 코스를 다른 사람이랑 처음 같이 뛴 날이에요. 좀 이상하지만, 형이 봐도 괜찮을 것 같아요.', branch: 'A' },
      { type: 'char', show: true, src: 'img/lp/haejun_entry/char_haejun_smile.png', branch: 'B' },
      { type: 'narration', text: '5분 더 쉬자는 권유에 옅게 끄덕인다. 자기는 권유 잘 안 받는 사람이다.', branch: 'B' },
      { type: 'lp', text: '...5분 더요. 좋네요. 그쪽이 권유하면 받아주게 되네요. 평소엔 다 거절하는데. 짜증날 만도 한데 짜증 안 나요. 그것도 처음이에요.', branch: 'B' },
      { type: 'bg', img: 'img/lp/haejun_entry/scene3.png' },
      { type: 'gm', text: '6km 코스 끝. 1시간 4분. 평소의 두 배. 그가 손목 시계를 본다.' },
      { type: 'char', show: true, src: 'img/lp/haejun_entry/char_haejun_badge.png' },
      { type: 'narration', text: '시계를 보고 한 번 옅게 웃는다. 회사에선 안 보이는 웃음.' },
      { type: 'lp', text: '두 배 걸렸어요. 1시간 4분. 그쪽이랑 같이 뛴 거니까 두 배가 두 배 같지 않네요. ...오늘은 1위 자리에 좀 늦게 갈게요. 7시 출근인데, 좀 늦어도 돼요. 처음 그래보는 거예요.' },
      { type: 'narration', text: '물병 두 개가 양손에 빈 채로 흔들린다. 자각 후 어색하게 한 번 웃는다.' },
      { type: 'lp', text: '내일 5시 30분, 또 같이 가실래요? 한 시간이면 좋겠어요. 32분은 이제 좀 짧게 느껴져서요.' },
      { type: 'end' }
    ],
    linked: [
      { type: 'narration', text: '다음날 새벽 5시 28분. 옥상 입구. 어제와 같은 자리. 그가 2분 일찍 와서 너를 기다리고 있다.' },
      { type: 'lp', text: '...오늘은 2분 일찍 왔어요. 그쪽이 먼저 도착해 있으면 어쩌나 해서요. 평소엔 정확히 30분에 도착하는데, 오늘은 그게 좀 어렵네요.' },
      { type: 'narration', text: '물병 두 개를 손에 들고, 그중 한 개를 너에게 건넨다. 어제와 같은 종류.' },
      { type: 'lp', text: '...어제 한 시간 동안 잘 잤어요. 4년 동안 잘 자던 사람인데, 어제는 그게 다른 종류로 잘 잤어요. 그쪽 페이스로 한 시간 뛴 게 머리를 좀 다른 데 두게 해주거든요. ...이건 그쪽한테만 한 말이에요. 다른 사람한텐 안 옮길게요.' }
    ]
  },

  kai: {
    title: '키캡 만지지 마',
    profileBg: 'img/lp/kai_entry/profile_bg.png',
    entryThumb: 'img/lp/kai_entry/scene1.png',
    rewards: [
      '감정 조각 +6',
      '싱크율 0% → 5%',
      '키메모리 해금: "어제 만진 키캡" / "1분간의 환풍구 정전"',
      '다음 주 화요일 새벽 2시 7분 정전 1분 약속'
    ],
    chat: [
      { type: 'image', src: 'img/lp/kai_entry/header.png', caption: '비 오는 밤 · 지하 작업실' },
      { type: 'narration', text: '비 오는 밤. 지하 작업실 문이 살짝 열려 있다. 카이가 모니터 너머로 한쪽 눈만 들어 너를 한 번 본다. 인사 없음. 짜증부터.' },
      { type: 'lp', text: '...뭘 봐. 키캡 처음 봐? 만지지 마.' },
      { type: 'narration', text: '책상 모서리에 새 키캡 박스. 흰빛이 모니터 푸른빛 사이에 한 점. 너의 시선이 그쪽에 닿자 곁눈질 한 번.' },
      { type: 'lp', text: '이 키캡, 그쪽이 어제 만진 거야. 닦았어. 닦았다고. ...왜 이걸 알려주고 있냐.' },
      { type: 'narration', text: '손가락으로 한 번 톡, 톡. 두 번. 소리가 정확히 같은 깊이로 두 번 떨어진다.' },
      { type: 'user', text: '키캡 안 만질게요. 닦으셨다는 거니까요.' },
      { type: 'narration', text: '피식. 짜증과 그게 묘하게 섞인 한 번. 모니터로 시선을 다시 돌린다.' },
      { type: 'lp', text: '...어. 그래. 안 만지면 됐어.' },
      { type: 'narration', text: '모니터 한 대를 끄고 한 대를 너 쪽으로 돌린다. 코드가 아니라 영상 한 컷이 떠 있다. 카메라로 찍은 환풍구.' },
      { type: 'lp', text: '이거 우리 집 환풍구. 비 오는 날엔 이 소리 깔리니까 작업 잘 돼. ...왜 이걸 너한테 보여주는지는 묻지 마.' },
      { type: 'user', text: '환풍구 영상까지 찍어요?' },
      { type: 'narration', text: '짧게 어깨를 으쓱. 후드 안쪽이 잠깐 보인다.' },
      { type: 'lp', text: '가끔. 비 안 올 때 들으려고. 이상하지. 알아. 나도 알아. ...됐어, 그 얘기는.' },
      { type: 'narration', text: '책상 한쪽에 미개봉 라면 봉지 두 개. 하나는 물기 묻은 자국으로 봐서 어제 들었다 놨다.' },
      { type: 'lp', text: '이번 주 두 번째야. 한 번 더 먹으면 진짜 망하는 거지. ...너도 먹을래? 안 먹으면 말고.' },
      { type: 'user', text: '먹을게요.' },
      { type: 'narration', text: '피식. 처음으로 정면으로 너를 본다. 짧게.' },
      { type: 'lp', text: '...어. 그래. 잘 골랐어. 안 골랐으면 안 끓였어.' },
      { type: 'narration', text: '의자에 등을 좀 더 기댄다. 키보드 위에 한 손을 가만히 올린다.' },
      { type: 'lp', text: '비 안 그칠 거야 오늘. 갈 거 아니면 거기 앉든가. ...본인 결정이야.' },
      { type: 'user', text: '한 번 더 와도 돼요?' },
      { type: 'narration', text: '모니터에 작은 창 하나가 뜬다. "통신 채널 대기" 표시. 카이가 키 한 번을 친다. 톡.' },
      { type: 'lp', text: '...채널 직접 여는 사람 거의 없어. 한 번 열어. 비 오는 밤만 와. 안 와도 상관없어. ...라고 말해야 되는 거 같은데, 와.' },
      { type: 'modal' }
    ],
    vn: [
      { type: 'bg', img: 'img/lp/kai_entry/scene1.png' },
      { type: 'char', show: false },
      { type: 'gm', text: '카이의 지하 작업실. 창문 닫힘. 비. 모니터 세 대 중 두 대는 코드, 한 대는 환풍구 영상. 책상 한쪽에 라면 봉지 두 개. 새 키캡 박스가 풀어 놓인 채로 한 시간째. 카이는 모니터 빛이 얼굴에 푸르게 비치는 자리에 앉아 있다.' },
      { type: 'char', show: true, src: 'img/lp/kai_entry/char_kai.png' },
      { type: 'narration', text: '카이가 새 키캡 한 개를 박스에서 꺼내 책상 위에 놓는다. 오른손 검지 한 번. 톡. 너를 보지 않는다.' },
      { type: 'lp', text: '이거 한정판이야. 너는 못 사. ...라고 하면 재수없겠지. 알아. 그래도 사실이야.' },
      { type: 'narration', text: '환풍구 영상을 켠 모니터에서 작은 회전음이 일정하게 들린다.' },
      { type: 'lp', text: '이 환풍구 4박이야. 한 박자에 한 키씩 누르면 코드 잘 써져. ...왜 너한테 알려주는지 모르겠어. 됐어, 들어봐.' },
      { type: 'narration', text: '키보드를 네 번 친다. 톡, 톡, 톡, 톡. 정확히 환풍구 회전과 맞는다.' },
      { type: 'user', text: '진짜 4박이네요.' },
      { type: 'lp', text: '...어. 알아. 그래서 산 거지. 처음 듣는 사람한테 이 얘기 한 적 거의 없어. 너 두 명째.' },
      { type: 'narration', text: '코드 화면을 한 번 슬쩍 너 쪽으로 보여준다. 변수명 하나만 빨갛게 떠 있다.' },
      { type: 'lp', text: '이런 시스템, 30분이면 뚫어. 다른 시스템 얘기야. 근데 이 빨간 변수 — 이번 주 내내 안 풀려. ...내 감정 복원하는 코드는 짜본 적도 없어. 짤 줄도 모르고. 그게 짜증나.' },
      { type: 'narrator', text: '이 사람이 자기 코드 막히는 거 누구한테 보여준 적 거의 없어요. 내가 알기로는, 동생한테도 안 보여줘요. 키캡도 안 만지게 하는 사람이에요.' },
      { type: 'bg', img: 'img/lp/kai_entry/scene2.png' },
      { type: 'gm', text: '카이가 의자에서 일어난다. 작은 가스레인지에 냄비를 올린다. 라면 봉지를 뜯는다. 두 번째다, 이번 주.' },
      { type: 'narration', text: '김이 올라온다. 그가 등을 보인 채로 묻는다.' },
      { type: 'lp', text: '너 매운 거 돼? ...안 되면 알아서 해.' },
      { type: 'user', text: '돼요.' },
      { type: 'lp', text: '...어. 다행이다. 안 매운 거 안 사니까.' },
      { type: 'narration', text: '면 한 젓가락을 그릇에 덜어 너 쪽으로 밀어준다. 자기 그릇은 작다. 본인은 안 인정한다.' },
      { type: 'lp', text: '너 그릇이 더 많아. 나는 두 번째라 입맛이 그래. ...뭐, 그렇다고. 먹어, 식기 전에.' },
      { type: 'narration', text: '너의 그릇 옆에 노란 무 두 조각을 작은 접시에 따로 놓아준다. 손이 정확하다.' },
      { type: 'lp', text: '무 두 조각. 한 조각은 부족, 세 조각은 짜. 두 조각이 정답이야. 내가 정한 거.' },
      { type: 'choices', options: [
        { label: '"여동생한테도 무 두 조각 계산해주세요?"', branch: 'A' },
        { label: '"라면 다음에 또 끓여줄 거예요?"', branch: 'B' },
        { label: '무 한 조각을 그의 그릇으로 옮긴다', branch: 'C' }
      ]},
      { type: 'char', show: true, src: 'img/lp/kai_entry/char_kai_smile.png', branch: 'C' },
      { type: 'narration', text: '카이는 자기 그릇 옆에 새로 올라온 무 한 조각을 한참 본다. 젓가락은 손에. 한 모금 국물. 짜증인지 뭔지 모를 표정.', branch: 'C' },
      { type: 'lp', text: '...야. 너 뭐 하는 거야. 무 옮긴 사람 처음 봐. 보통은 그냥 다 먹거나 남기거나 해. 옮긴 사람 너 처음이라고.', branch: 'C' },
      { type: 'narration', text: '국물 한 모금. 그릇을 내려놓는다. 무 한 조각은 안 치운다.', branch: 'C' },
      { type: 'lp', text: '...안 치울 거야 그거. 한 명만 한 거니까. 또 옮기지는 마. 한 번이야. 한 번만이라고.', branch: 'C' },
      { type: 'char', show: true, src: 'img/lp/kai_entry/char_kai_smile.png', branch: 'A' },
      { type: 'lp', text: '...동생 얘기 하지 마. 오늘은. 키캡 얘기로 끝내. 너 그거 본 적도 없잖아.', branch: 'A' },
      { type: 'char', show: true, src: 'img/lp/kai_entry/char_kai_smile.png', branch: 'B' },
      { type: 'lp', text: '...다음에 또 끓일게. 비 오는 날만. 너 안 와도 상관없어. ...라고 말은 했는데, 와.', branch: 'B' },
      { type: 'bg', img: 'img/lp/kai_entry/scene3.png' },
      { type: 'gm', text: '갑자기 환풍구 회전이 한 번 멎는다. 1분간의 정전. 모니터 세 대가 모두 검정으로 떨어진다. 작업실 안에 카이의 호흡 소리만 남는다.' },
      { type: 'char', show: true, src: 'img/lp/kai_entry/char_kai_badge.png' },
      { type: 'narration', text: '카이가 가만히 앉아 있다. 모니터 끄지 말라고 입버릇처럼 말하던 사람인데. 이번엔 그냥 가만히.' },
      { type: 'lp', text: '...환풍구 멈추니까 내 호흡 소리만 들리네. 이 소리 4년 만이야. ...너 며칠 안 오면 작업 효율 떨어져. 그게 너 때문이라고는 안 할 거야. 절대 안 할 거야.' },
      { type: 'narration', text: '비상등 빛에 손가락이 잠깐 보인다. 키보드 위에 그대로. 키캡 — 그쪽이 어제 만진 그 키캡.' },
      { type: 'lp', text: '1분이면 다시 켜져. 매주 한 번. 내가 직접 재봤어. 정확히 1분이야. ...왜 안 자고 이걸 재고 있는지는 묻지 마.' },
      { type: 'narration', text: '너 쪽으로 한 번 시선이 짧게.' },
      { type: 'lp', text: '다음 주 비 오는 화요일 새벽 2시 7분에 또 정전. 그 1분에 너 와 있어. ...안 오면 진짜 화 안 낼 거지만, 오라고.' },
      { type: 'end' }
    ],
    linked: [
      { type: 'narration', text: '오후. 비는 그쳤다. 그릇 두 개가 책상 위에 그대로 있다.' },
      { type: 'lp', text: '어제 그릇 안 치웠어. 무 한 조각 그대로 있어. ...왜 안 치웠냐고는 묻지 마. 답할 말 없어.' },
      { type: 'narration', text: '모니터에 작은 알림 하나. 화요일 새벽 2시 7분 카운트다운. 키캡 한 개가 책상 한가운데에 있다.' },
      { type: 'lp', text: '...키캡, 어제 너 만진 자리 그대로 안 닦았어. 닦았다고 거짓말한 거야. ...됐어, 묻지 마. 잠 좀 자. 비 안 와도 와.' }
    ]
  },

  jian: {
    title: '당신 수준에서',
    profileBg: 'img/lp/jian_entry/profile_bg.png',
    entryThumb: 'img/lp/jian_entry/scene1.png',
    rewards: [
      '감정 조각 +6',
      '싱크율 0% → 5%',
      '키메모리 해금: "두 번째 각도로 돌린 의자" / "빈 칸 옆 손가락"',
      '다음 주 화요일 저녁 7시 40분 약속'
    ],
    chat: [
      { type: 'image', src: 'img/lp/jian_entry/header.png', caption: '저녁 7시 40분 · 서버실 입구' },
      { type: 'narration', text: '저녁 7시 40분. 서버실 입구. 동료들은 다 퇴근했고 지안 혼자 안경을 한 번 고친다. 너의 발걸음에 시선만 정확히 너에게.' },
      { type: 'lp', text: '...누구 통해서 오셨어요? 여긴 그냥 들어오는 데 아니에요.' },
      { type: 'narration', text: '대답을 기다리지 않고 의자 등받이를 한 번 만진다. 각도를 한 번 바꾼다.' },
      { type: 'lp', text: '이 시스템 보러 오신 거면 미리 말씀드릴게요. 그쪽 수준으론 이해 안 돼요. 그래도 한 번 보여드리죠. 제가 시간 빼는 건 처음이에요.' },
      { type: 'user', text: '결함 어디예요?' },
      { type: 'narration', text: '짧은 침묵. 처음으로 입꼬리가 한 번 올라간다. 의외라는 톤.' },
      { type: 'lp', text: '...직설적이시네요. 보통은 "어떤 시스템이에요?"부터 묻는데. 결함 위치는 그쪽 영역이 아니에요. 죄송할 일은 아니고요.' },
      { type: 'narration', text: '책상 위 연필을 한 번 만진다. 손가락 끝이 검다. 시선은 안 준다.' },
      { type: 'lp', text: '이 연필, 방금 깎았어요. 끝이 너무 뾰족하면 부러져요. 적당히 둔하게 — 이게 제 기준이에요. 그쪽 기준이 아니라.' },
      { type: 'narration', text: '연필 끝을 보여준다. 정말 살짝 둔하다. 자기 자만이 그 끝에 다 있다.' },
      { type: 'user', text: '정확히 둔하네요.' },
      { type: 'narration', text: '잠시 너를 본다. 안경을 한 번 더 고친다.' },
      { type: 'lp', text: '...알아보시는 분이 처음이에요. 보통은 "왜 이렇게 깎았어요?" 묻거든요. 그쪽한텐 답변 안 해도 되겠네요.' },
      { type: 'narration', text: '차가운 물을 한 모금. 잔을 정확히 같은 자리에 내려놓는다.' },
      { type: 'lp', text: '저녁 이 시간 이 자리는 제 거예요. 회식 안 가요. 그 시간이 제일 집중되거든요. 그쪽한테는 굳이 안 가는 이유 설명 안 할게요.' },
      { type: 'user', text: '한 번 더 와도 돼요?' },
      { type: 'narration', text: '주머니에서 작은 스케치북을 꺼낸다. 펼치진 않고 책상 위에 놓는다. 시선은 너에게 정면.' },
      { type: 'lp', text: '...와요. 저녁 7시 40분 이 자리, 일주일에 네 번 비어요. 그쪽이 정확한 시간에 오면 채널 열어드려요. 늦으면 안 열어요. 한 번만이에요.' },
      { type: 'modal' }
    ],
    vn: [
      { type: 'bg', img: 'img/lp/jian_entry/scene1.png' },
      { type: 'char', show: false },
      { type: 'gm', text: '서버실 안. 저녁 7시 40분. 형광등은 한 줄만. 지안의 책상 위엔 연필·차가운 물·스케치북·새 의자. 모니터엔 코드 한 화면, 빨간 변수명 하나. 본인이 4년째 운영하는 시스템이다.' },
      { type: 'char', show: true, src: 'img/lp/jian_entry/char_jian.png' },
      { type: 'narration', text: '지안이 너에게 차가운 물을 한 잔 따라준다. 컵 가장자리에 정확히 절반.' },
      { type: 'lp', text: '절반이에요. 그쪽이 흔들면 더 따라요. 안 흔들면 그대로.' },
      { type: 'narration', text: '모니터를 너 쪽으로 살짝 돌린다. 빨간 변수명이 한 줄.' },
      { type: 'lp', text: '이게 제가 만든 시스템이에요. 학생들의 감정을 수치화해요. 4년 운영했어요. 그쪽 수준으론 이해 안 될 거예요. ...아니, 미안해요. 지금 그 말은 제가 듣기 싫어서 먼저 한 거예요.' },
      { type: 'narration', text: '의자 등받이를 손가락으로 한 번 만지고 다시 손을 내린다. 각도가 다섯 번째.' },
      { type: 'lp', text: '이 의자, 등받이 각도 다섯 번 바꿨어요. 두 번째가 편하다는 거 알아요. 근데 두 번째에서 멈추면 더 좋은 걸 못 본 거잖아요. 그건 제 기준에 안 맞아요.' },
      { type: 'user', text: '다섯 번째까지 와도 두 번째로 못 돌아가요?' },
      { type: 'narration', text: '짧은 침묵. 손가락 끝이 책상 가장자리를 한 번 살짝 두드린다. 처음으로 입꼬리만.' },
      { type: 'lp', text: '...그 질문, 보통 사람들은 안 해요. 그냥 "어떤 게 제일 좋은데?" 묻죠. ...괜찮네요, 그쪽.' },
      { type: 'narrator', text: '이 사람이 자기 의자 각도를 다섯 번째까지 다 말한 건 의자 산 후 처음이에요. 보통 두 번째쯤에서 듣는 사람을 잘라냅니다.' },
      { type: 'bg', img: 'img/lp/jian_entry/scene2.png' },
      { type: 'gm', text: '지안이 스케치북을 천천히 펼친다. 펼친 페이지엔 자기 시스템 구조도가 연필로 그려져 있다. 빈 칸 옆에는 작은 글씨로 숫자 다섯 개만 적혀 있다. 단계 표시.' },
      { type: 'narration', text: '스케치북을 너 쪽으로 천천히 밀어준다. 손은 페이지 모서리만 잡고 있다.' },
      { type: 'lp', text: '이게 제 시스템 구조예요. 안쪽부터 결함이 시작돼요. 1단계, 2단계는 저만 알아요. 3단계가 되면 다른 사람들도 보는데, 그땐 이미 늦어요.' },
      { type: 'narration', text: '옆에 적힌 숫자 다섯 개를 손끝으로 가리킨다.' },
      { type: 'lp', text: '4년 동안 이 결함, 저 혼자 알았어요. 폭로하면 제가 살인자가 돼요. 안 하면 시스템이 사람들 감정을 계속 수치화해요. 둘 다 제 책임이에요.' },
      { type: 'narration', text: '연필을 한 번 만진다. 깎은 끝이 살짝 둔한 그 연필. 처음으로 안경을 벗는다.' },
      { type: 'lp', text: '이 시스템의 가장 큰 결함은… 제가 양심을 가졌다는 거예요. 자만이 제 보호막이고요. 도도한 거 아니에요. ...아니, 맞아요. 그건 인정해요.' },
      { type: 'narration', text: '짧게 멈춤. 차가운 물 한 모금. 잔이 정확한 자리.' },
      { type: 'lp', text: '...그쪽이 옆에 있어서 이 결함이 보였어요. 4년 동안 안 보였어요. 한 번만 인정할게요. 다른 사람한텐 평생 안 할 말이에요.' },
      { type: 'choices', options: [
        { label: '"3단계가 뭔지 말해주세요"', branch: 'A' },
        { label: '"의자 두 번째 각도로 돌리세요"', branch: 'B' },
        { label: '빈 칸 옆에 손가락을 가만히 댄다', branch: 'C' }
      ]},
      { type: 'char', show: true, src: 'img/lp/jian_entry/char_jian_smile.png', branch: 'C' },
      { type: 'narration', text: '지안은 너의 손가락이 빈 칸에 닿은 자리를 한참 본다. 자기 손은 페이지 모서리에. 호흡이 한 번 길어진다. 표정이 한 번 흐려진다.', branch: 'C' },
      { type: 'lp', text: '...빈 칸을 가만히 둔 사람 처음이에요. 보통은 "거기에 뭐 들어가요?" 묻고 답을 받아내려고 해요. 그쪽은 안 묻네요.', branch: 'C' },
      { type: 'narration', text: '짧게 멈춤. 의자 등받이 다이얼을 돌린다. 다섯 번째에서 두 번째로.', branch: 'C' },
      { type: 'lp', text: '두 번째로 돌렸어요. 4년 만이에요. 그쪽 앞이라 한 거예요. 다음에 또 이러진 마세요.', branch: 'C' },
      { type: 'char', show: true, src: 'img/lp/jian_entry/char_jian_smile.png', branch: 'A' },
      { type: 'lp', text: '3단계는 오늘 말 안 해요. 아직 그쪽 영역 아니에요. 다음 주에 와요, 그때 들을 자격 있는지 봐드릴게요.', branch: 'A' },
      { type: 'char', show: true, src: 'img/lp/jian_entry/char_jian_smile.png', branch: 'B' },
      { type: 'lp', text: '...두 번째로 돌리라는 건 그쪽이 결정하실 일은 아닌데요. ...그래도 오늘은 그쪽 말 들어드려요. 한 번만이에요.', branch: 'B' },
      { type: 'bg', img: 'img/lp/jian_entry/scene3.png' },
      { type: 'gm', text: '형광등이 한 번 더 깜빡이고 안정된다. 지안이 차가운 물을 마저 한 모금 마신다. 안경을 다시 쓴다. 도도한 톤이 다시 돌아온다.' },
      { type: 'char', show: true, src: 'img/lp/jian_entry/char_jian_badge.png' },
      { type: 'narration', text: '너 쪽으로 시선이 한 번 정면. 옅게 웃는다, 두 번째 미소다.' },
      { type: 'lp', text: '다음 주 화요일 저녁 7시 40분에 와요. 의자 두 번째 각도로 둘게요. 그쪽 자리도 만들어두죠. 늦지는 마요. 시간 못 지키면 자격 없어요.' },
      { type: 'end' }
    ],
    linked: [
      { type: 'narration', text: '새벽 3시 12분. 잠이 안 와서 모니터를 다시 켰다. 어제 그쪽이 본 페이지가 펼쳐져 있다.' },
      { type: 'lp', text: '...의자 두 번째 각도로 두니까 편해요. 4년 만에 두 번째로 돌린 거예요. 그쪽 때문이라고는 안 할게요. ...아니, 그쪽 때문이에요. 한 번만 인정.' },
      { type: 'narration', text: '짧은 멈춤. 화면에 시스템 구조도가 떠 있다. 빈 칸 그대로.' },
      { type: 'lp', text: '다음 주 화요일까지 그 빈 칸 안 채울 거예요. 그쪽이 와서 옆에 손가락만 다시 대줘요. 그게 어제 한 거니까 두 번째도 한 번 더.' }
    ]
  },

  nia: {
    title: '새벽 첫 지하철의 녹음기',
    profileBg: 'img/lp/nia_entry/profile_bg.png',
    entryThumb: 'img/lp/nia_entry/scene1.png',
    rewards: [
      '감정 조각 +6',
      '싱크율 0% → 5%',
      '키메모리 해금: "안 누른 빨간 버튼" / "한 정거장의 4분 12초"',
      '다음 화요일 새벽 4시 30분 카페 약속'
    ],
    chat: [
      { type: 'image', src: 'img/lp/nia_entry/header.png', caption: '새벽 4시 38분 · 24시 카페' },
      { type: 'narration', text: '새벽 4시 38분. 24시 카페. 사람은 너랑 그녀뿐. 니아는 한 손에 녹음기를 들고 있고 다른 손은 검은 커피 잔. 너의 발걸음에 시선이 한 번 정확히 너에게.' },
      { type: 'lp', text: '안 켜요, 걱정 마요.' },
      { type: 'narration', text: '녹음기를 책상 위에 천천히 내려놓는다. 빨간 불은 꺼진 채.' },
      { type: 'lp', text: '이 시간에 어떻게 여기 있어요? 잠 안 와서?' },
      { type: 'user', text: '잠 안 와서요.' },
      { type: 'narration', text: '피식. 짧게. 한쪽 귀의 이어폰을 빼서 책상 위에 놓는다.' },
      { type: 'lp', text: '새벽 4시 반에 잠 안 와서 카페 있는 사람들은 보통 두 종류예요. 일이 있어서. 아니면 일이 없어서.' },
      { type: 'narration', text: '녹음기 옆 카세트 두 개 중 하나를 손가락으로 한 번 만진다.' },
      { type: 'lp', text: '저는 일 있어서요. 5시 23분 첫 지하철 타고 한 정거장만 가요. 그 한 정거장이 비어 있어서.' },
      { type: 'user', text: '빈 지하철에 뭐가 있어요?' },
      { type: 'narration', text: '짧은 멈춤. 검은 커피 한 모금. 잔을 정확한 자리에.' },
      { type: 'lp', text: '비어 있는 게 있어요. 그게 다예요. 새벽 첫 차는 사람도, 음악도, 점원도 안 봐줘서요. 그쪽이 한 번 타보면 알 거예요.' },
      { type: 'narration', text: '녹음기를 다시 손에 든다. 빨간 불 안 켜고 그냥 손에.' },
      { type: 'lp', text: '항상 들고 다녀요. 안 들고 나가면 손이 허전해요. 켜는 건 한 달에 두 번쯤. 나머진 그냥 들고 있어요.' },
      { type: 'user', text: '한 달에 두 번도 많은 거 같은데요.' },
      { type: 'narration', text: '처음으로 길게 본다. 녹음기를 책상 위에 다시 놓는다.' },
      { type: 'lp', text: '...그 말 좀 무섭게 했네요. 보통은 한 달에 두 번이면 적다고 해요. 그럼 그쪽한텐 한 달에 두 번이 많아요?' },
      { type: 'narration', text: '카세트 두 개 중 하나를 너 쪽으로 살짝 밀어준다. 라벨에 작은 글씨로 날짜 한 줄.' },
      { type: 'lp', text: '어제 인터뷰 거예요. 안 들어봐도 돼요. 그냥 책상 위에 한 번 놨다가 가져갈 거예요. 이게 제 루틴이에요. 이상하다고 생각해도 돼요.' },
      { type: 'user', text: '한 번 더 와도 돼요?' },
      { type: 'narration', text: '녹음기 옆에 너의 잔이 놓일 자리를 손가락으로 한 번 가리킨다.' },
      { type: 'lp', text: '새벽 4시 30분에 일주일에 세 번 와요. 화·금·일. 그쪽 잔 자리 여기. 첫 지하철 같이 한 정거장 타볼래요?' },
      { type: 'modal' }
    ],
    vn: [
      { type: 'bg', img: 'img/lp/nia_entry/scene1.png' },
      { type: 'char', show: false },
      { type: 'gm', text: '새벽 5시 21분. 지하철역 첫 차 플랫폼. 안내 방송이 한 번 들어왔다. 사람은 둘만. 니아의 손에 녹음기. 빨간 불은 꺼져 있다. 멀리서 레일 위 바퀴 한 번 닿는 소리.' },
      { type: 'char', show: true, src: 'img/lp/nia_entry/char_nia.png' },
      { type: 'narration', text: '첫 차가 들어온다. 빈 칸이 그대로 비어 있다. 니아가 한 칸 앞으로 그냥 걸어 들어간다.' },
      { type: 'lp', text: '이 칸이 항상 제일 비어요. 두 번째 칸. 첫 칸은 가끔 사람 있고 세 번째 칸도. 이게 제 자리예요.' },
      { type: 'narration', text: '플라스틱 좌석에 앉는다. 너에게 옆자리를 손짓.' },
      { type: 'lp', text: '한 정거장만 갈 거예요. 정확히 4분 12초. 그 동안 그쪽이 무슨 말 해도 돼요. 안 해도 돼요.' },
      { type: 'user', text: '무슨 말 했으면 좋겠어요?' },
      { type: 'narration', text: '녹음기를 무릎 위에 올려놓는다. 빨간 불 여전히 꺼져 있다.' },
      { type: 'lp', text: '...그쪽이 잠 못 자는 이유 같은 거. 안 물어볼게요. 보통 새벽 첫 차에 같이 탄 사람한테는 안 물어요. 4분 12초가 짧기도 하고요.' },
      { type: 'narration', text: '지하철 문이 닫히고 바퀴가 한 번 끼익. 창문 밖이 캄캄해진다.' },
      { type: 'lp', text: '이게 제일 좋아요. 창밖이 어두운 거. 음악 없는 거. 누가 사진 안 찍는 거.' },
      { type: 'narrator', text: '이 사람이 새벽 첫 차에 누구를 같이 데려온 건 6년 동안 처음이에요. 동료 기자도 안 데려와요.' },
      { type: 'bg', img: 'img/lp/nia_entry/scene2.png' },
      { type: 'narration', text: '녹음기를 손가락으로 한 번 만진다. 빨간 버튼 위에서 멈춘다. 누르지 않는다.' },
      { type: 'lp', text: '...이거 한 번 누른 적 있어요. 6년 전에. 그게 제 첫 인터뷰였어요. 새벽 첫 차에서, 누군가가 한 말을 받았어요.' },
      { type: 'narration', text: '짧게 멈춤. 손가락이 빨간 버튼에서 떨어진다.' },
      { type: 'lp', text: '그땐 진실을 알면 그게 정의라고 생각했어요. ...라기보단, 그렇게 안 생각하면 일이 안 됐어요.' },
      { type: 'user', text: '지금은요?' },
      { type: 'narration', text: '창밖을 본다. 검정 터널. 한 번 깜빡이는 형광등.' },
      { type: 'lp', text: '지금은 한 달에 두 번만 눌러요. 진실을 알면 의무가 돼요. 한 번 들으면 안 들은 척 못 하고, 한 번 받으면 안 받은 척 못 하고. 그래서 켜기 전에 오래 안 켜고 있어요.' },
      { type: 'narration', text: '녹음기를 너 쪽으로 살짝 보여준다.' },
      { type: 'lp', text: '그쪽 무릎 위에 한 번 놔봐요. 켜는 건 안 해도 돼요. 그냥 잠깐만.' },
      { type: 'choices', options: [
        { label: '"한 달에 두 번 누른 거 한 번만 들려주세요"', branch: 'A' },
        { label: '"안 켜고 그냥 놓을 자리 만들게요"', branch: 'B' },
        { label: '녹음기를 받아 무릎 위에 가만히 놓는다', branch: 'C' }
      ]},
      { type: 'char', show: true, src: 'img/lp/nia_entry/char_nia_smile.png', branch: 'C' },
      { type: 'narration', text: '니아는 너의 무릎 위에 놓인 녹음기를 한참 본다. 자기 손은 무릎 옆에. 검은 커피 잔은 카페에 두고 왔다.', branch: 'C' },
      { type: 'lp', text: '...받고도 안 누르는 사람 처음이에요. 보통은 받으면 호기심에 한 번 눌러봐요. 안 눌러도 신기해서 만지긴 해요.', branch: 'C' },
      { type: 'narration', text: '짧은 침묵. 창밖에서 다음 정거장 불빛이 흐릿하게 보이기 시작한다.', branch: 'C' },
      { type: 'lp', text: '진실이라는 게요. 누르는 사람이 정해지는 게 아니라, 안 누르는 사람이 정해지는 거 같아요. 6년 동안 누르는 사람만 봤거든요. 그쪽도 이 전파 듣고 있죠. 그 목소리가… 정말 진짜일까요?', branch: 'C' },
      { type: 'char', show: true, src: 'img/lp/nia_entry/char_nia_smile.png', branch: 'A' },
      { type: 'lp', text: '...오늘은 안 들려줄게요. 한 달에 두 번이 끝났어요. 다음 화요일에 와요. 그땐 안 들려줘도 옆에 있어줄래요?', branch: 'A' },
      { type: 'char', show: true, src: 'img/lp/nia_entry/char_nia_smile.png', branch: 'B' },
      { type: 'lp', text: '...그 자리, 카페에. 만들어둘게요. 다음 화요일에 와요.', branch: 'B' },
      { type: 'bg', img: 'img/lp/nia_entry/scene3.png' },
      { type: 'gm', text: '안내 방송: "다음 정거장. 종착역." 지하철 속도가 천천히 줄어든다. 4분 12초가 거의 다 됐다.' },
      { type: 'char', show: true, src: 'img/lp/nia_entry/char_nia_badge.png' },
      { type: 'narration', text: '너의 무릎 위 녹음기를 천천히 다시 받아간다. 빨간 버튼은 누르지 않는다.' },
      { type: 'lp', text: '종착역이에요. 여기서 내려서 한 정거장 걸어 돌아가요. 그게 제 루틴이에요. 한 정거장은 타고, 한 정거장은 걸어요.' },
      { type: 'narration', text: '플랫폼에 내려서서, 녹음기를 안주머니에 넣는다. 카세트 라벨이 잠깐 보인다.' },
      { type: 'lp', text: '다음 화요일 새벽 4시 30분 카페에. 그쪽 무릎 위에 녹음기 한 번 더 놓을게요. 그땐 한 정거장 더 가볼래요?' },
      { type: 'narration', text: '짧은 끄덕임. 처음으로 옅게 웃는다. 짧게.' },
      { type: 'lp', text: '...오늘은 안 들어도 잘 잘 수 있을 거 같아요. 그쪽도 잠 좀 자요.' },
      { type: 'end' }
    ],
    linked: [
      { type: 'narration', text: '밤 11시 47분. 카세트 한 개를 막 다 들었다. 라벨에 어제 새벽 날짜.' },
      { type: 'lp', text: '어제 새벽에 안 누른 거, 오늘 밤에 한 번 누르고 다시 들었어요. 그쪽이 무릎 위에 놓고 안 누른 그 4분 12초.' },
      { type: 'narration', text: '짧은 침묵. 녹음기 빨간 불이 한 번 꺼진다.' },
      { type: 'lp', text: '안 누른 시간이 녹음기 안에 한 번 더 들어있더라고요. 무음으로요. 6년 동안 무음 트랙은 한 번도 안 들어봤거든요. ...이거 좀 신경 쓰여요.' }
    ]
  },

  levi: {
    title: '마이크 끄고 난 직후',
    profileBg: 'img/lp/levi_entry/profile_bg.png',
    entryThumb: 'img/lp/levi_entry/scene1.png',
    rewards: [
      '감정 조각 +5',
      '싱크율 0% → 5%',
      '키메모리 해금: "같은 자리 다른 4박" / "12분 같이 사탕"',
      '다음 송출 종료 30분 약속'
    ],
    chat: [
      { type: 'image', src: 'img/lp/levi_entry/header.png', caption: '방음실 · ON-AIR 막 꺼진 직후' },
      { type: 'narration', text: '방음실 문이 열린다. 빨간 ON-AIR가 막 꺼졌다. 송출이 끝난 직후의 공기. 레비가 헤드폰을 목으로 내리고 노트 한 페이지를 너 쪽으로 보여준다. 글씨는 작고 정확하다.' },
      { type: 'lp', text: '*(노트에 적어 보여주며)* 안녕. 사탕?' },
      { type: 'narration', text: '책상 위 노란 사탕 봉지에서 한 알을 꺼내 너에게 내민다. 손목까지 내려온 흰 후디 소매.' },
      { type: 'user', text: '받을게요.' },
      { type: 'narration', text: '옅게 끄덕인다. 노트에 다음 줄을 쓴다. 펜은 검은색. 글씨는 또박또박.' },
      { type: 'lp', text: '*(노트)* 노란 거 새로 왔어. 어제. 빨간 거는 다음 주에.' },
      { type: 'narration', text: '헤드폰을 한 번 만진다. 새 패드 냄새가 흰 후디 옷깃에 살짝 묻어 있다.' },
      { type: 'lp', text: '*(노트)* 패드 새 거. 냄새 좋아. 만져봐도 돼.' },
      { type: 'user', text: '정말 좋네요. 폴리우레탄 같은 향이에요.' },
      { type: 'narration', text: '처음으로 시선이 정면으로. 깊고 부드러운 검은 눈. 노트에 다음 줄을 쓴다. 한 글자가 잠깐 멈춘다.' },
      { type: 'lp', text: '*(노트)* 그 단어 처음 들었어. 폴 리 우 레 탄.' },
      { type: 'narration', text: '손가락으로 책상 위에 박자를 두드린다. 톡, 톡, 톡, 톡.' },
      { type: 'lp', text: '*(노트)* 이거 4박. 들려?' },
      { type: 'user', text: '들려요. 일정해요.' },
      { type: 'narration', text: '노트에 빠르게 한 줄.' },
      { type: 'lp', text: '*(노트)* 보통 사람들은 3박이라고 해. 4박인 줄 모르고.' },
      { type: 'narration', text: '노트를 한 페이지 넘긴다. 새 페이지엔 작은 그림. 헤드폰 위에서 떨어진 사탕 한 알.' },
      { type: 'lp', text: '*(노트)* 이거 어제 그렸어. 사탕이 떨어지는 박자. 4박.' },
      { type: 'user', text: '한 번 더 와도 돼요?' },
      { type: 'narration', text: '노트에 글씨가 한 번 멈췄다 다시 시작된다. 입술은 안 움직인다.' },
      { type: 'lp', text: '*(노트)* 송출 끝나고 30분만. 그때만 문 열려. 글로만 답할 수 있어. 괜찮아?' },
      { type: 'narration', text: '짧게 끄덕이고, 너에게 노란 사탕 한 알을 더 손바닥에 올려준다.' },
      { type: 'lp', text: '*(노트)* 가져가. 다음에 가져오면 잊을 거 같아서.' },
      { type: 'modal' }
    ],
    vn: [
      { type: 'bg', img: 'img/lp/levi_entry/scene1.png' },
      { type: 'char', show: false },
      { type: 'gm', text: '방음실. 송출 종료 1분 후. 빨간 ON-AIR는 꺼져 있다. 마이크 가운데 그대로. 헤드폰 새 패드 냄새가 공기 안에 있다. 레비가 노트를 무릎 위에 펼친 채로 앉아 있다. 책상 위 노란 사탕 봉지 한 줄.' },
      { type: 'char', show: true, src: 'img/lp/levi_entry/char_levi.png' },
      { type: 'narration', text: '레비가 노트 새 페이지를 펼친다. 가운데에 작은 그림 하나. 마이크 메탈 그릴 클로즈업.' },
      { type: 'lp', text: '*(노트)* 이 마이크. 5년째. 한 번도 안 바뀌었어.' },
      { type: 'narration', text: '손가락 끝으로 마이크를 한 번 살짝 두드린다. 톡. 무음.' },
      { type: 'lp', text: '*(노트)* 마이크 켜져 있을 땐 내 목소리가 누군가가 제일 듣고 싶은 말이 돼. 꺼져 있을 때는… 그냥 마이크야. 내가 하고 싶은 말은 뭘까. 5년째 모르겠어.' },
      { type: 'narration', text: '노트에 다음 줄을 쓴다.' },
      { type: 'lp', text: '*(노트)* 30분 후에 다시 켜야 해. 그 30분이 제일 좋아. 마이크가 그냥 마이크일 때.' },
      { type: 'user', text: '30분 동안 뭘 해요?' },
      { type: 'narration', text: '노트에 한 단어. "사탕"' },
      { type: 'lp', text: '*(노트)* 사탕 한 알. 노란 거. 입에서 녹는 데 12분 걸려.' },
      { type: 'narration', text: '책상 위 사탕 봉지에서 한 알을 꺼낸다. 너에게 한 알. 자기 입에 한 알.' },
      { type: 'lp', text: '*(노트, 입엔 사탕)* 같이 12분.' },
      { type: 'narrator', text: '이 사람이 송출 후 30분에 사탕을 누구랑 같이 먹은 적 5년 동안 처음이에요. 관리자도 안 와요, 그 시간엔.' },
      { type: 'bg', img: 'img/lp/levi_entry/scene2.png' },
      { type: 'gm', text: '사탕이 입에서 녹는 12분. 레비가 노트를 한 페이지 넘긴다. 빈 페이지. 손가락으로 박자를 두드린다. 4박. 4박. 4박.' },
      { type: 'narration', text: '노트에 박자를 따라 점을 찍는다. ·  ·  ·  ·' },
      { type: 'lp', text: '*(노트)* 박자가 좋아. 박자는 거짓말 안 해.' },
      { type: 'narration', text: '너 쪽으로 펜을 내민다. 다른 손으로 노트 빈 페이지를 가리킨다.' },
      { type: 'lp', text: '*(노트, 빠르게)* 너도 한 번. 4박.' },
      { type: 'user', text: '어떻게 칠까요?' },
      { type: 'narration', text: '옅게 미소. 사탕 때문에 한쪽 볼이 살짝 부풀어 있다. 노트에 글씨.' },
      { type: 'lp', text: '*(노트)* 아무렇게나. 너의 4박은 내 거랑 다를 거야. 그게 보고 싶어.' },
      { type: 'narration', text: '너의 손가락을 잠깐 본다. 펜을 너에게 내민 채로.' },
      { type: 'lp', text: '*(노트)* 송출용 4박 5년 동안 똑같이 쳐. 너 거는 처음이라.' },
      { type: 'choices', options: [
        { label: '펜으로 노트에 점 4개를 찍는다', branch: 'A' },
        { label: '손가락으로 책상에 4박을 직접 두드린다', branch: 'B' },
        { label: '레비의 손가락 박자를 같은 자리에 따라 친다', branch: 'C' }
      ]},
      { type: 'char', show: true, src: 'img/lp/levi_entry/char_levi_smile.png', branch: 'C' },
      { type: 'narration', text: '레비는 너의 손가락이 같은 자리를 두드리는 순간을 한참 본다. 자기 박자가 한 박 흔들린다. 사탕이 입에서 녹는 게 잠시 멈춘 듯이.', branch: 'C' },
      { type: 'lp', text: '*(노트, 한 박 늦게)* ...같은 자리. 다른 4박.', branch: 'C' },
      { type: 'narration', text: '노트 새 페이지를 펼친다. 빈 페이지에 작은 글씨로 한 줄.', branch: 'C' },
      { type: 'lp', text: '*(노트)* 5년 동안 4박을 들은 사람은 많아. 같이 친 사람은 너야. 내 감정이 모두를 위로한대. 그럼 내 감정은 뭐지. 너의 한 박이 답이 될까?', branch: 'C' },
      { type: 'narration', text: '짧게 멈춤. 사탕이 입에서 마저 녹는다.', branch: 'C' },
      { type: 'lp', text: '*(노트)* 나도 박자를 모르던 시절이 있었어. 14살 전에.', branch: 'C' },
      { type: 'char', show: true, src: 'img/lp/levi_entry/char_levi_smile.png', branch: 'A' },
      { type: 'lp', text: '*(노트)* 점 4개 좋아. 너의 점은 모서리가 살짝 기울었어. 내 거는 한 줄로 똑같고.', branch: 'A' },
      { type: 'char', show: true, src: 'img/lp/levi_entry/char_levi_smile.png', branch: 'B' },
      { type: 'lp', text: '*(노트)* 책상 4박 좋아. 손바닥 두꺼워서 소리가 더 깊어.', branch: 'B' },
      { type: 'bg', img: 'img/lp/levi_entry/scene3.png' },
      { type: 'gm', text: '빨간 ON-AIR 표시등 옆에 작은 카운트다운이 켜진다. 30분이 거의 다 됐다. 다음 송출 5분 전.' },
      { type: 'char', show: true, src: 'img/lp/levi_entry/char_levi_badge.png' },
      { type: 'narration', text: '너 쪽으로 마지막 한 페이지를 천천히 보여준다. 가운데에 작은 그림. 두 손가락이 같은 자리를 두드리는 순간.' },
      { type: 'lp', text: '*(노트)* 이거 다음 송출 끝나고 그릴 거야. 30분 후에.' },
      { type: 'narration', text: '너에게 노란 사탕 한 알을 더. 손바닥에. 손가락 끝이 살짝 닿는다.' },
      { type: 'lp', text: '*(노트)* 다음 송출 끝나고 30분 후에 또 와. 같이 4박 한 번 더 쳐. 너 거 한 박. 내 거 한 박.' },
      { type: 'end' }
    ],
    linked: [
      { type: 'narration', text: '송출이 막 끝났다. 노트에 새 그림이 그려져 있다. 두 손가락이 같은 자리를 두드리는 순간. 한 손가락 옆에 작은 글씨로 "너".' },
      { type: 'lp', text: '*(노트, 막 그린 그림 옆에 새로 적은 한 줄)* 4박이 한 박 흔들렸어. 송출 중에. 5년 만에 처음.' },
      { type: 'narration', text: '짧은 멈춤. 노트 다음 줄.' },
      { type: 'lp', text: '*(노트)* 30분 시작했어. 노란 사탕 두 개 꺼내놨어. 하나는 너 거.' }
    ]
  },

  damya: {
    title: '야, 너 뭐 보냐',
    profileBg: 'img/lp/damya_entry/profile_bg.png',
    entryThumb: 'img/lp/damya_entry/scene1.png',
    rewards: [
      '감정 조각 +7',
      '싱크율 0% → 5%',
      '키메모리 해금: "라면 봉지의 종이 8초" / "받쳐 든 어묵 국물"',
      '모레 밤 자정 5분 전 다른 노점 약속'
    ],
    chat: [
      { type: 'image', src: 'img/lp/damya_entry/header.png', caption: '밤 11시 50분 · 외곽 떡볶이 노점' },
      { type: 'narration', text: '밤 11시 50분. 외곽 골목 끝 떡볶이 노점. 사람 한 명 더 끼면 좁은 자리. 담야가 너의 발걸음 한 번에 시선이 위에서 아래로 한 번 훑는다. 거친 톤.' },
      { type: 'lp', text: '야, 너 뭐 봐. 노점 처음 봐? ...됐고. 누가 보냈어.' },
      { type: 'user', text: '야, 너야말로 뭐 보는데. 떡볶이 먹으러 왔어.' },
      { type: 'narration', text: '짧게 너를 한 번 더 스캔. 출구 쪽으로 시선이 한 번. 입꼬리 한쪽이 한 번 올라간다.' },
      { type: 'lp', text: '...어. 빨리 답하네. 좋아. 망설이는 새끼들 보면 짜증나거든. 너 합격.' },
      { type: 'narration', text: '노점 아저씨한테 손가락 두 개. 떡볶이 일 인분 추가. 본인이 먼저 시켰다.' },
      { type: 'lp', text: '이 집 매워. 너 매운 거 돼? ...안 되면 저쪽 가서 우유 사와. 내가 한 입 더 먹게.' },
      { type: 'user', text: '돼. 우유 안 사와.' },
      { type: 'narration', text: '피식. 짧게. 떡볶이 한 입 먼저 입에 넣고 어묵 국물 한 모금.' },
      { type: 'lp', text: '...됐어. 매운 거 안 되는 새끼는 다음 노점으로 보내거든. 너 자리 생겼어.' },
      { type: 'narration', text: '노점 가장자리에 등을 기댄다. 출구 쪽이 정확히 보이는 자리.' },
      { type: 'lp', text: '이 시간 좋아. 차도 안 다니고 발소리만 들려. ...근데 너 발 너무 시끄러워. 골목 끝에서부터 네 걸음 다 들었어.' },
      { type: 'user', text: '걸음 소리로 구분돼?' },
      { type: 'narration', text: '짧은 침묵. 갈색 눈이 너를 한 번 더 똑바로 본다.' },
      { type: 'lp', text: '...야. 그것도 빨리 묻네. 보폭, 무게, 좌우 균형. 너 한쪽으로 살짝 기울었어. 알아? 운동 안 해서 그런 거야.' },
      { type: 'narration', text: '떡볶이 한 입 더. 매운 게 입가에 묻는다. 손등으로 한 번 닦는다.' },
      { type: 'lp', text: '새 통신 장비 어제 샀어. 비싸. 너는 못 사. ...아, 너 사라는 거 아니야. 그냥 그렇다고. 추적 안 돼야 해서 산 거니까.' },
      { type: 'user', text: '한 번 더 와도 돼?' },
      { type: 'narration', text: '떡볶이 종이접시를 너 쪽으로 한 번 더 밀어준다. 어묵 국물 컵도.' },
      { type: 'lp', text: '...야. 와. 안 오면 내가 찾으러 갈 거니까. 이 노점은 두 번째 안전가옥 근처야. 일주일에 두세 번 와. 발소리로 기억해둘게. 다음에도 빨리 답해. 한 번이라도 망설이면 너 다음 노점이야.' },
      { type: 'modal' }
    ],
    vn: [
      { type: 'bg', img: 'img/lp/damya_entry/scene1.png' },
      { type: 'char', show: false },
      { type: 'gm', text: '외곽 골목 떡볶이 노점. 자정 5분 전. 노점 빨간 등 한 개. 노점 아저씨는 라디오 작게 켜놓고 졸고 있다. 담야의 자리는 출구 쪽과 골목 안쪽을 동시에 볼 수 있는 모서리. 종이접시 위 떡볶이 일 인분, 어묵 국물 두 컵.' },
      { type: 'char', show: true, src: 'img/lp/damya_entry/char_damya.png' },
      { type: 'narration', text: '떡볶이 한 입을 너 쪽으로 밀어준다. 자기는 어묵 국물.' },
      { type: 'lp', text: '야. 이 집 떡 두꺼워. 일 인분 일곱 개. 다른 집은 아홉 개인데 얇아. ...됐어, 그냥 먹어.' },
      { type: 'narration', text: '자기 어묵 컵을 한 모금. 시선은 골목 끝.' },
      { type: 'lp', text: '5분 전부터 골목 안쪽 발자국 하나 들려. 우리 동지 중 한 명이야. 신경 꺼. 곧 다른 골목으로 빠져.' },
      { type: 'user', text: '항상 누가 있어?' },
      { type: 'narration', text: '짧은 멈춤. 시선이 너에게 정면으로. 빠른 호흡.' },
      { type: 'lp', text: '5년째 그래. 몇 명인지는 몰라. 내 동선만 안 들키면 돼. ...편 안 골라도 돼. 근데 망설이는 거 자체가 이미 편 고른 거야. 알지? 몰라도 돼. 알려줄 시간은 있어.' },
      { type: 'narration', text: '재킷 안주머니에서 종이 한 장 끝을 잠깐 살짝 보여준다. 안 펼친다.' },
      { type: 'lp', text: '오늘 안전가옥 위치야. 내가 8초 안에 외우면 노점 아저씨가 라면 봉지 끓는 물에 넣을 거야. 5년 동안 제일 빠른 방법.' },
      { type: 'narrator', text: '이 사람이 자기 안전가옥 위치를 누구한테 보여준 거 5년 동안 처음이에요. 동지들한테도 종이 자체로는 안 보여줘요. 너한테만 보여주는 거예요.' },
      { type: 'bg', img: 'img/lp/damya_entry/scene2.png' },
      { type: 'gm', text: '노점 아저씨가 라면 끓는 냄비 위로 봉지 한 장을 들고 온다. 담야가 안주머니에서 종이를 꺼내 한 번만 더 본다. 외운다. 정확히 8초. 종이를 봉지에 넣는다. 봉지가 끓는 면 위로.' },
      { type: 'narration', text: '종이가 라면 봉지 안에서 빠르게 흐물해진다. 8초 만에 알아볼 수 없게.' },
      { type: 'lp', text: '5년 동안 제일 빠른 방법이야. 봉지 안 종이는 누가 봐도 면 받침이라고 생각해. 똑똑하지 이거.' },
      { type: 'narration', text: '어묵 국물 한 모금. 시선이 너에게.' },
      { type: 'lp', text: '너한테 보여준 거 이상하지? 알아. 처음 본 새끼한테 안 보여주는 게 정상이야. ...근데 너 발 균형 얘기 들었을 때 바로 답했잖아.' },
      { type: 'user', text: '그래서?' },
      { type: 'narration', text: '짧은 침묵. 정확한 한 번 호흡. 시선이 더 길게 머문다.' },
      { type: 'lp', text: '...야. 5년 만에 처음 보는 새끼야 너. 망설이는 거 못 견디는데, 너 한 번도 안 망설였어. 그게 다야. ...라고 하면 신파잖아. 신파 아니야.' },
      { type: 'narration', text: '떡볶이 한 입. 매운 게 입가에 묻는다. 이번엔 손등으로 닦지 않는다.' },
      { type: 'lp', text: '23살까지 나도 성적표만 봤어. 지금은 발자국만 봐. ...저 전광판 봐. 누군가의 감정이 수치로 떠 있어. 우리 동생도 저기 한 줄이었어. 이게 이상하지 않다고 하면 너 진짜 실망이야.' },
      { type: 'choices', options: [
        { label: '"23살에 무슨 일이 있었어?"', branch: 'A' },
        { label: '"안전가옥 위치 다음에도 보여줘"', branch: 'B' },
        { label: '어묵 국물 컵을 한 번 더 받쳐 들어준다', branch: 'C' }
      ]},
      { type: 'char', show: true, src: 'img/lp/damya_entry/char_damya_smile.png', branch: 'C' },
      { type: 'narration', text: '담야는 너의 손이 컵을 받쳐 든 자리를 한참 본다. 자기 손은 재킷 안주머니에 그대로. 짧게 멈춘 호흡.', branch: 'C' },
      { type: 'lp', text: '...야. 컵 받쳐 든 새끼 5년 만에 두 번째야. 첫 번째는 동생. 동생이 감정 데이터 낮다고 강등당하던 날이었어. 그때부터 지금까지 아무도 안 받쳤어.', branch: 'C' },
      { type: 'narration', text: '어묵 국물 컵을 너의 손 위에서 받아 든다. 한 모금. 천천히.', branch: 'C' },
      { type: 'lp', text: '...너 이름 뭐였지. 어, 너. 너만 듣고 있어. 다른 새끼한텐 이거 안 해. 한 번도 안 했어. ...됐어, 떡볶이 마저 먹어. 식는다.', branch: 'C' },
      { type: 'char', show: true, src: 'img/lp/damya_entry/char_damya_smile.png', branch: 'A' },
      { type: 'lp', text: '...야. 23살 얘기 다음에. 오늘은 떡볶이 식는다. 빨리 답하는 새끼한테 무거운 얘기 안 던져.', branch: 'A' },
      { type: 'char', show: true, src: 'img/lp/damya_entry/char_damya_smile.png', branch: 'B' },
      { type: 'lp', text: '...모레 밤 다른 노점에서. 그때 종이 한 장 더 보여줄게. 외워. 8초. 너 머리 좋잖아.', branch: 'B' },
      { type: 'bg', img: 'img/lp/damya_entry/scene3.png' },
      { type: 'gm', text: '자정. 멀리서 첨탑 종이 한 번 울린다. 라디오에서 노점 아저씨가 작게 켜둔 다음 곡이 흐른다. 골목 안쪽 발자국이 다른 골목으로 빠지는 소리가 들린다.' },
      { type: 'char', show: true, src: 'img/lp/damya_entry/char_damya_badge.png' },
      { type: 'narration', text: '너 쪽으로 정면으로 한 번 본다. 옅게 미소 한 점, 입꼬리만.' },
      { type: 'lp', text: '야. 다음 노점은 모레 밤 같은 시간 다른 가옥 근처. 너 와. 안 오면 내가 찾아. 아직 못 본 게 많거든.' },
      { type: 'narration', text: '재킷 안주머니에서 작은 종이 한 장 끝을 또 잠깐 보여준다. 위치는 안 보인다.' },
      { type: 'lp', text: '이번엔 봉지 안 넣고 너한테 한 번 보여줄게. 외워. 8초. 그게 다야. 늦으면 안 기다려.' },
      { type: 'end' }
    ],
    linked: [
      { type: 'narration', text: '새벽 4시 17분. 두 번째 안전가옥. 매트리스 끝에 앉아서.' },
      { type: 'lp', text: '야. 어제 네 발소리 또 들렸어. 새벽 1시쯤 골목 두 칸 떨어진 데서. 잘못 들었나 했어. 발소리 잘못 들은 거 5년 만에 처음이야.' },
      { type: 'narration', text: '짧은 침묵. 통신 장비 한 번 점검.' },
      { type: 'lp', text: '아침에 노점 가서 떡볶이 한 입 먼저 했어. 네 자리 비어 있어서 좀 이상했어. ...신파 아니야. 그냥 그렇다고. 모레 밤 와. 잠 좀 자.' }
    ]
  },

  lise: {
    title: '7시 12분의 자판기',
    profileBg: 'img/lp/lise_entry/profile_bg.png',
    entryThumb: 'img/lp/lise_entry/scene1.png',
    rewards: [
      '감정 조각 +6',
      '싱크율 0% → 5%',
      '키메모리 해금: "두 캔 7.2cm" / "안 보낸 한 줄 로그"',
      '모레 저녁 7시 12분 자판기 약속'
    ],
    chat: [
      { type: 'image', src: 'img/lp/lise_entry/header.png', caption: '저녁 7시 12분 · 감정 관제국 33층 자판기 앞' },
      { type: 'narration', text: '저녁 7시 12분. 33층 자판기 앞 복도. 사무실 형광등이 6500K로 정확히 깔린다. 리제가 캔이 떨어지는 짧은 음을 한 번 듣고, 워치를 본다. 너의 발걸음이 들리자 워치를 한 번 더, 너에게 한 번 더.' },
      { type: 'lp', text: '지금 시간이… 일곱 시 십이 분이네요. 야근하시나요?' },
      { type: 'narration', text: '캔커피를 자판기 입구에서 꺼낸다. 정확한 한 손으로.' },
      { type: 'lp', text: '죄송해요, 인사가 좀 이상했네요. 시간을 먼저 봐서. 보통 처음 보는 분께 이렇게 안 인사하는데… 어, 죄송합니다.' },
      { type: 'user', text: '시간 본 게 인사 같았어요.' },
      { type: 'narration', text: '짧은 침묵. 워치 화면이 7:13으로 바뀐다.' },
      { type: 'lp', text: '...그렇게 받아주시는 분 처음이에요. 보통은 약간 당황하세요. 시간 인사라는 거.' },
      { type: 'narration', text: '자판기 옆 메뉴 디스플레이를 한 번 본다. 새 메뉴 표시 한 줄.' },
      { type: 'lp', text: '오늘 새 베이글이 들어왔어요. 시금치 베이글. ...음, 시금치는 좀 무리네요. 평소에 먹던 걸로 할게요.' },
      { type: 'narration', text: '플레인 베이글 버튼을 누른다. 5년째 같은 자리.' },
      { type: 'lp', text: '이 자판기 5년 동안 매일 7시 12분에 와요. 정확히. 몇 번 7시 13분에 온 적 있는데, 그날은 업무 속도가 0.4초 늦어진 날이에요. 워치에 로그가 남아요.' },
      { type: 'user', text: '0.4초가 늦은 거예요? 평균 편차가 어떻게 되는데요?' },
      { type: 'narration', text: '잠시 워치를 본다. 손목 안쪽으로 가렸다가 다시 너에게.' },
      { type: 'lp', text: '...0.4초는 굉장히 큰 수치예요. 5년 평균 편차가 0.05초인데. 오늘은 0.7초예요. 지금 이 순간 기준으로요.' },
      { type: 'narration', text: '캔커피를 한 모금. 베이글 봉지를 정확히 같은 자리에 들고.' },
      { type: 'lp', text: '죄송, 데이터 얘기가 또 나왔네요. 지금 제 집중도가 한 십몇 퍼센트쯤 떨어진 것 같아요. 자판기 앞에 5년 만에 처음 누가 같이 서 있어서, 좀… 정확하질 않네요.' },
      { type: 'user', text: '한 번 더 와도 돼요?' },
      { type: 'narration', text: '워치를 한 번 더 본다. 7:14. 정확한 한 호흡.' },
      { type: 'lp', text: '...관제실은 출입 제한이지만 자판기 앞 복도는 아니에요. 7시 12분에 여기가 비어요. 5년 동안 그랬어요. 그 시간에 와주시면, 제 워치에 그쪽 발걸음 시간이 자동으로 기록될 거예요. 그건 제가 안 지울게요.' },
      { type: 'modal' }
    ],
    vn: [
      { type: 'bg', img: 'img/lp/lise_entry/scene1.png' },
      { type: 'char', show: false },
      { type: 'gm', text: '감정 관제국 33층 복도. 저녁 7시 12분. 형광등 6500K가 흰 벽 위로 정확하게 떨어진다. 자판기 한 대. 캔커피 새 진열 줄. 베이글 진열 한 줄. 리제의 워치가 7:12로 정확히 표시된다.' },
      { type: 'char', show: true, src: 'img/lp/lise_entry/char_lise.png' },
      { type: 'narration', text: '자판기 앞에서 너의 캔과 자기 캔을 두 캔 같이 뽑는다. 두 번째는 너 거.' },
      { type: 'lp', text: '...오늘 처음으로 두 캔을 같이 뽑았어요. 5년 동안 한 캔이었어요. 어색하네요, 데이터상으로도.' },
      { type: 'narration', text: '너에게 캔을 한 손으로 정확하게 건넨다. 손가락 끝이 닿지 않는 거리.' },
      { type: 'lp', text: '차가워요. 자판기 안쪽이 17도예요. 마실 때 손이 시리실 거예요.' },
      { type: 'user', text: '5년 동안 한 캔이었으면, 이 자리도 한 자리만 비어 있겠네요.' },
      { type: 'narration', text: '짧은 멈춤. 워치를 한 번 본다. 7:13.' },
      { type: 'lp', text: '...그쪽이 지금 서 계신 자리가 정확히 한 자리예요. 자판기 앞이 사람 두 명 서기엔 좁거든요. 그쪽이 거기 서신 게 5년 만에 처음이에요.' },
      { type: 'narration', text: '자판기 옆 작은 의자 두 개를 가리킨다. 한 자리는 5년째 빈 자리.' },
      { type: 'lp', text: '의자 두 개 있어요. 한 자리는 5년 동안 제가 앉았어요. 다른 자리는 비어 있었어요. 그쪽이 앉으셔도 돼요. 데이터상 처음으로 두 자리가 다 차게 돼요.' },
      { type: 'narrator', text: '이 사람이 자판기 앞 의자 빈 자리에 누가 앉기를 5년 동안 한 번도 권한 적 없어요. 동료들도 잘 모르는 자리예요.' },
      { type: 'bg', img: 'img/lp/lise_entry/scene2.png' },
      { type: 'gm', text: '두 사람이 의자에 앉는다. 리제의 캔이 7시 14분에 첫 모금. 그녀의 워치 화면에 새 로그 한 줄이 자동으로 추가된다. "동행 1명 / 7:14:02 / 자판기 복도 / 집중 수치 -0.7초"' },
      { type: 'narration', text: '워치 화면을 너 쪽으로 살짝 돌려 보여준다. 안 가린다 이번엔.' },
      { type: 'lp', text: '보세요. 7:14:02에 집중 수치가 -0.7초 떨어졌어요. 이게 새 로그예요.' },
      { type: 'narration', text: '손가락으로 한 줄을 가리킨다.' },
      { type: 'lp', text: '5년 동안 이 시간대 -0.05초였거든요. 0.7초는… 14배예요. 평균의 14배.' },
      { type: 'narration', text: '짧은 호흡. 캔커피 한 모금.' },
      { type: 'lp', text: '보통 이런 데이터 나오면 즉시 시스템에 보고해야 해요. 14배 편차는 시스템 자체 결함 의심 수치거든요.' },
      { type: 'user', text: '보고했어요?' },
      { type: 'narration', text: '짧은 침묵. 워치를 한 번 더 본다. 손목 안쪽으로 가리지 않는다.' },
      { type: 'lp', text: '...아직 안 했어요. 5년 동안 안 보낸 적 없는데. 오늘 7시 14분 02초 이 한 줄은… 일부러 안 보내고 있어요.' },
      { type: 'narration', text: '고개를 한 번 살짝 너 쪽으로. 처음으로 시선이 정면.' },
      { type: 'lp', text: '그땐 저도 0.7초 같은 거 안 들킬 만큼 정확한 사람이 아니었어요. 5년 전 입사 첫 주에는요.' },
      { type: 'choices', options: [
        { label: '"5년 전 첫 주에 무슨 일이 있었어요?"', branch: 'A' },
        { label: '"그 한 줄 다음 주에도 안 보낼 거예요?"', branch: 'B' },
        { label: '캔을 그녀의 캔 옆에 같은 거리로 내려놓는다', branch: 'C' }
      ]},
      { type: 'char', show: true, src: 'img/lp/lise_entry/char_lise_smile.png', branch: 'C' },
      { type: 'narration', text: '리제는 두 캔의 같은 거리를 한참 본다. 워치를 한 번 보고 다시 캔으로.', branch: 'C' },
      { type: 'lp', text: '...두 캔 사이가 정확히 7.2cm예요. 제가 5년 동안 한 캔만 둘 때 자판기와 의자 사이가 7.2cm였거든요. 그쪽이 그 거리를 그대로 옮겼어요.', branch: 'C' },
      { type: 'narration', text: '짧은 호흡. 옅게 미소. 입꼬리만.', branch: 'C' },
      { type: 'lp', text: '보고 안 할 거예요. 오늘 한 줄. 내일도. 모레도. 그쪽이 7시 12분에 오시는 동안은 안 보낼 거예요.', branch: 'C' },
      { type: 'narration', text: '워치 화면을 한 번 더 본다. 새 로그 한 줄이 또 추가된다. "두 캔 같은 거리 / 7:18:45"', branch: 'C' },
      { type: 'lp', text: '이 로그도 안 보낼 거예요. 제가 직접 만든 비공개 폴더에 저장했어요. 5년 동안 비공개 폴더 안 만들던 사람이 오늘 처음 만들었어요.', branch: 'C' },
      { type: 'char', show: true, src: 'img/lp/lise_entry/char_lise_smile.png', branch: 'A' },
      { type: 'lp', text: '...첫 주는 다음에 말할게요. 오늘은 워치 한 줄 추가가 14건째예요. 그게 답이에요.', branch: 'A' },
      { type: 'char', show: true, src: 'img/lp/lise_entry/char_lise_smile.png', branch: 'B' },
      { type: 'lp', text: '...안 보낼 거예요. 그쪽이 7시 12분에 오시는 동안은. 데이터상 오시는 게 더 정확해요.', branch: 'B' },
      { type: 'bg', img: 'img/lp/lise_entry/scene3.png' },
      { type: 'gm', text: '7시 22분. 워치에 다음 일정 알림 한 줄. "관제실 복귀 7:30 / 야근 22:00까지" 자판기 위 작은 디지털 시계가 같은 시간을 가리킨다.' },
      { type: 'char', show: true, src: 'img/lp/lise_entry/char_lise_badge.png' },
      { type: 'narration', text: '의자에서 일어난다. 7.2cm 거리는 그대로 두고.' },
      { type: 'lp', text: '관제실 복귀 시간이에요. 8분 늦으면 워치에 또 로그가 남거든요. ...라기보단, 그쪽 옆에 더 앉아 있고 싶다는 데이터가 지금 워치에 막 추가되고 있어요. 아주 정확한 수치로요.' },
      { type: 'narration', text: '너 쪽으로 짧게 끄덕임. 미소는 옅지만 두 번째다.' },
      { type: 'lp', text: '모레 7시 12분에 또 오세요. 두 캔 같이 뽑아둘게요. 의자 두 자리 다 비워둘게요. 7.2cm 거리도요.' },
      { type: 'end' }
    ],
    linked: [
      { type: 'narration', text: '새벽 1시 47분. 야근 끝났다. 비공개 폴더 안에 새 로그 두 줄이 추가됐다.' },
      { type: 'lp', text: '오늘 7시 12분 이후로 워치에 로그가 14줄 추가됐어요. 모두 그쪽 관련이에요. 보고 안 했어요. 5년 동안 14줄을 한 번에 안 보낸 적 없거든요.' },
      { type: 'narration', text: '짧은 호흡. 워치를 한 번 더 본다.' },
      { type: 'lp', text: '...집중 수치가 야근 내내 평소보다 +20% 위였어요. 오류가 한 건도 없었어요. 0.7초 떨어진 게 오류로 안 이어졌어요. 이건 제가 5년 동안 본 데이터에 없는 패턴이에요. 모레 7시 12분이… 좀 빨리 왔으면 좋겠어요.' }
    ]
  },

  lana: {
    title: '빈 무대에서',
    profileBg: 'img/lp/lana_entry/profile_bg.png',
    entryThumb: 'img/lp/lana_entry/scene1.png',
    rewards: [
      '감정 조각 +7',
      '싱크율 0% → 5%',
      '키메모리 해금: "두 번째 줄 두 번째 마디" / "무대 바닥의 한 뼘 거리"',
      '모레 새벽 3시 녹음실 약속'
    ],
    chat: [
      { type: 'image', src: 'img/lp/lana_entry/header.png', caption: '새벽 2시 7분 · Black Static 무대 뒤' },
      { type: 'narration', text: '새벽 2시 7분. 무대 뒤 좁은 통로. 무대 위 앰프가 막 꺼졌다. 라이브 끝나고 관객 대부분이 빠진 직후. 라나가 수건으로 목을 닦으며 너 쪽으로 시선을 끊지 않고. 도발 톤.' },
      { type: 'lp', text: 'Black Static. 빈 무대 정리 30분, 옆에 누구 두는 거 처음이에요. 어떻게 해드릴까요.' },
      { type: 'narration', text: '수건을 어깨에 걸친 채 베이스를 스탠드에 정확히 기대놓는다. 새 줄이 한 번 짧게 울린다.' },
      { type: 'lp', text: '...아직 안 갔네. 박수도 안 쳤으면서. 그래서 더 좋았어요.' },
      { type: 'user', text: '박수 안 친 게 왜 좋아요?' },
      { type: 'narration', text: '루비 레드 눈동자가 무대 위 핑크 네온 잔향 사이에서 한 점 또렷하게. 시선 안 끊는다.' },
      { type: 'lp', text: '오늘 곡 듣고 무슨 생각 했어요? 별로였으면 더 말해줘요. 좋았다고 하면 그쪽이 거짓말한 거예요. 내 곡은 좋게 들으라고 쓴 게 아니거든요.' },
      { type: 'narration', text: '베이스 줄을 한 번 손가락으로 만진다. 어제 갈았다는 그 줄.' },
      { type: 'lp', text: '어제 갈았어요. 첫날이 제일 단단해요. ...만져볼래요? 손가락 찔려요. 그거 좀 보고 싶어서.' },
      { type: 'user', text: '만질게요.' },
      { type: 'narration', text: '손가락 끝으로 줄 위를 한 번 짚어준다. 너의 손가락 위에. 손은 잡지 않는다. 시선만.' },
      { type: 'lp', text: '거기. 두 번째 줄. 그 자리가 제일 단단해요. 박자 놓친 게 그 줄에서였어요. ...그게 더 정직했죠.' },
      { type: 'narration', text: '콜라 캔을 한 손으로 딴다. 5분 안에 다 마실 거 같다. 첫 모금이 길다. 시선은 안 끊는다.' },
      { type: 'lp', text: '라이브 끝나면 콜라 한 캔. 5분 안에. 거기 앉아서 보고 있어요. 일어서지 말고요.' },
      { type: 'user', text: '5분 후엔 뭐 해요?' },
      { type: 'narration', text: '콜라 캔을 들고 무대 쪽을 한 번 본다. 빈 무대. 케이블 정리 안 된 채.' },
      { type: 'lp', text: '빈 무대 정리. 30분. 그게 두 번째 무대예요. 라이브보다 그게 더 좋아요. ...이거 들킨 적 없어요. 그쪽한테는 들켰네요. 박수 안 친 사람한테만 들켜요.' },
      { type: 'narration', text: '너 쪽으로 시선이 다시. 옅게, 입꼬리만 한 번.' },
      { type: 'lp', text: '레비는 듣고 싶은 말을 불러요. 나는 듣기 싫은 말만 곡으로 써요. 누가 더 정직한지는… 내 곡 끝까지 들은 사람만 알아요. 그쪽은 들었잖아요.' },
      { type: 'user', text: '한 번 더 와도 돼요?' },
      { type: 'narration', text: '콜라 한 모금. 캔이 절반 비었다. 짧은 침묵. 시선은 안 끊는다.' },
      { type: 'lp', text: '...새 곡 있어요. 가사가 그쪽 보면서 쓴 거예요. 다른 사람한텐 안 들려줘요. 모레 새벽 3시, 녹음실. 들을래요? 듣고 나면 못 빠져나가요. 그래도요?' },
      { type: 'modal' }
    ],
    vn: [
      { type: 'bg', img: 'img/lp/lana_entry/scene1.png' },
      { type: 'char', show: false },
      { type: 'gm', text: 'Black Static 라이브 하우스. 새벽 2시 12분. 관객 마지막 한 명이 출구를 지나갔다. 무대 위 핫핑크 네온 두 줄, 보라 한 줄. 케이블이 무대 바닥에 풀린 채로. 마이크 스탠드는 비스듬. 라이브 직후 35도였던 공기가 천천히 식어간다.' },
      { type: 'char', show: true, src: 'img/lp/lana_entry/char_lana.png' },
      { type: 'narration', text: '라나가 무대 위로 올라간다. 너에게 무대 가장자리 한 자리를 손가락으로 한 번 가리킨다. 시선은 안 끊는다.' },
      { type: 'lp', text: '거기 앉아요. 무대 가장자리. 일어서지 말고. 빈 무대에서 나만 보이게 할까요, 둘 다 보이게 할까요. 골라요.' },
      { type: 'narration', text: '케이블 한 줄을 손에 감기 시작한다. 정확한 박자로 한 바퀴, 두 바퀴. 시선은 안 끊는다.' },
      { type: 'lp', text: '케이블 감는 데 12분. 앰프 끄는 데 5분. 마이크 스탠드 위치 8분. 정확히 25분. 5분 남아요. 그 5분이 그쪽 거예요.' },
      { type: 'narration', text: '너 쪽으로 시선이 한 번 더. 케이블 감는 손은 안 멈춘다.' },
      { type: 'lp', text: '5분 동안 그냥 무대 가장자리에 앉아 있어요. 콜라 마저 마시고. 손은 무릎 위에. 그게 다예요. ...라고 하면 그쪽이 일부러 손 안 올리겠죠.' },
      { type: 'user', text: '5분 동안 뭐 생각해요?' },
      { type: 'narration', text: '케이블 한 바퀴 더. 짧은 멈춤. 입꼬리 한쪽이 올라간다.' },
      { type: 'lp', text: '...다음 곡 생각 안 해요. 보통 다들 다음 곡 생각할 거라고 하는데, 아니에요. 그냥 케이블 감는 박자랑 콜라 식는 속도, 그쪽 시선이 어디 가 있는지만 봐요.' },
      { type: 'narrator', text: '이 사람이 빈 무대 30분에 누구를 들인 거 처음이에요. 매니저도 안 와요, 이 시간엔. "위로해줄게요" 하는 사람은 1초 만에 잘립니다.' },
      { type: 'bg', img: 'img/lp/lana_entry/scene2.png' },
      { type: 'gm', text: '라나가 케이블을 다 감았다. 12분. 앰프 두 대를 차례로 끈다. 5분. 마이크 스탠드 위치를 정확히 무대 가운데로. 8분. 정확히 25분. 5분이 남는다. 라나가 콜라 캔을 들고 무대 가장자리에 앉는다. 너 옆에. 한 뼘 거리.' },
      { type: 'narration', text: '콜라 캔을 한 모금. 잔량이 줄어든다. 5분이 시작됐다.' },
      { type: 'lp', text: '첫 곡 박자 안 놓쳤어요. 두 번째 곡에서 놓쳤어요. 두 번째 줄, 두 번째 마디.' },
      { type: 'narration', text: '손가락으로 베이스 두 번째 줄을 한 번 짚는다. 멀리서 짧은 음.' },
      { type: 'lp', text: '...박수 안 친 거 봤어요. 그래서 더 좋았어요. 다른 사람들이 박수 친 곡은 내가 거짓말한 곡이에요. 박자 놓친 그 마디만 진짜였어요.' },
      { type: 'user', text: '다음 라이브엔 다시 안 갈아요?' },
      { type: 'narration', text: '짧게 피식. 콜라 한 모금 더. 시선이 너에게 정면.' },
      { type: 'lp', text: '...그쪽 좀 제정신 아니네요. 보통은 다음엔 잘하라고 해요. 그쪽은 줄을 갈지 말지를 물어. 그게 더 좋아요.' },
      { type: 'narration', text: '콜라 캔을 무대 바닥에 정확하게 내려놓는다. 너의 자리에서 한 뼘 거리.' },
      { type: 'lp', text: '안 갈아요. 일주일 동안 두 번째 줄로 한 번 더 놓쳐볼래요. ...내 곡 듣고 기분 좋아진 사람 한 명도 없어요. 그쪽도 좋아하려 하지 마요. 끝까지 들어만 줘요. 그거면 돼요.' },
      { type: 'narration', text: '짧은 침묵. 무대 위 핫핑크 네온 한 줄이 한 번 깜빡인다. 초커를 손끝으로 한 번 쓸어내린다.' },
      { type: 'lp', text: '레비는 듣고 싶은 말을 불러요. 나는 듣기 싫은 말만 곡으로 써요. 누가 더 정직한지는… 내 곡 끝까지 들은 사람만 알아요. 그쪽은 들었잖아요.' },
      { type: 'choices', options: [
        { label: '"내 곡 끝까지 들은 게 어때서요?"', branch: 'A' },
        { label: '"두 번째 줄 다음 주에도 안 갈 거예요?"', branch: 'B' },
        { label: '무대 바닥 콜라 캔 옆에 손을 가만히 댄다', branch: 'C' }
      ]},
      { type: 'char', show: true, src: 'img/lp/lana_entry/char_lana_smile.png', branch: 'C' },
      { type: 'narration', text: '라나는 너의 손이 콜라 캔 옆 무대 바닥에 놓인 자리를 한참 본다. 자기 손은 무릎 위에. 핑크 하이라이트가 이마에서 떨어진다. 안 정리한다. 시선만 너에게.', branch: 'C' },
      { type: 'lp', text: '...무대 자체에 손 댄 관객 처음이에요. 보통은 나한테 손을 대거나 내 베이스에 손을 대지. 무대에 손 댄 그쪽은 좀 다른 종류네요.', branch: 'C' },
      { type: 'narration', text: '짧은 호흡. 무대 위 마이크 스탠드 쪽을 한 번 본다. 다시 너에게.', branch: 'C' },
      { type: 'lp', text: '새 곡 있어요. 가사가 그쪽 보면서 쓴 거예요. 한 마디만 들려줄게요. 다음은 녹음실에서. 듣고 나면 못 빠져나가요. ...그쪽 그거 알면서 와야 해요.', branch: 'C' },
      { type: 'char', show: true, src: 'img/lp/lana_entry/char_lana_smile.png', branch: 'A' },
      { type: 'lp', text: '...끝까지 들은 게 어때서, 라고 받아치는 그쪽이 더 도발이에요. 새 곡 한 마디는 녹음실에서. 모레 새벽 3시. 늦지 마요.', branch: 'A' },
      { type: 'char', show: true, src: 'img/lp/lana_entry/char_lana_smile.png', branch: 'B' },
      { type: 'lp', text: '...안 갈 거예요. 다음 주까지. 두 번째 줄로 한 번 더 놓쳐볼래요. 그쪽 또 박수 안 치고 듣고 있어요. 그래주면 돼요.', branch: 'B' },
      { type: 'bg', img: 'img/lp/lana_entry/scene3.png' },
      { type: 'gm', text: '빈 무대. 새벽 2시 32분. 라나가 마이크 안 켜고 베이스 한 마디만 친다. 두 번째 줄, 두 번째 마디. 5초의 음. 한 번만.' },
      { type: 'char', show: true, src: 'img/lp/lana_entry/char_lana_badge.png' },
      { type: 'narration', text: '5초의 음이 사라진 후, 베이스를 다시 스탠드에. 너 쪽으로 한 번 끄덕임. 옅게, 두 번째 미소다.' },
      { type: 'lp', text: '한 마디. 그게 다예요. 다음 마디는 모레 새벽 녹음실에서. 그쪽 안 와도 다른 사람 안 들려줘요. 그래서 와야 해요.' },
      { type: 'narration', text: '무대에서 내려와 너의 옆에 다시 앉는다. 콜라 캔을 마저 비운다. 5분이 거의 다 됐다.' },
      { type: 'lp', text: '모레 새벽 3시. 녹음실 위치 보낼게요. 와서 두 번째 줄 다시 만져봐요. 한 마디 더 들려줄게요. ...듣고 나면 못 빠져나가요. 그래도요.' },
      { type: 'end' }
    ],
    linked: [
      { type: 'narration', text: '오후 5시 28분. 막 일어났다. 베이스 두 번째 줄을 한 번 짚어보고 손을 뗀다.' },
      { type: 'lp', text: '...어제 친 한 마디가 안 잊혀요. 보통 라이브 끝나면 한두 시간이면 잊는데. 이건 12시간째 머릿속에 있어요. 그쪽이 박수 안 친 게 제일 시끄러웠어요.' },
      { type: 'narration', text: '짧은 침묵. 악보에 한 마디 더 그어 넣는다.' },
      { type: 'lp', text: '새 곡 한 마디 더 만들었어요. 그쪽 와서 두 번째 줄 만지고 나면, 들려줄 거예요. 모레 새벽 3시 녹음실. 거기 좁아요. 그쪽 옆에 다른 사람 자리 없어요. 그래도 와요.' }
    ]
  }

});
